version: '3.1'

services:
  db:
    build: ./database
    image: giphy-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: giphy
      MYSQL_PASSWORD: codegiphy123
      MYSQL_DATABASE: GIPHY
  api:
     build: ./code-challenge-svc
     depends_on:
        - db
     ports:
        - "8080:8080"
        - "9990:9990"
     image: giphy-api
     container_name: giphy-api_1