version: '3.1'

services:
  db:
	 build: .
    image: giphy-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: giphy
      MYSQL_PASSWORD: codegiphy123
      MYSQL_DATABASE: GIPHY
